//REGISTER ACTIONS
export const REGISTER_RIGHT = "REGISTER_RIGHT";
export const REGISTER_WRONG = "REGISTER_WRONG";
// LOGIN ACTIONS
export const LOGIN_RIGHT = "LOGIN_RIGHT";
export const LOGIN_WRONG = "LOGIN_WRONG";
//AUTH USER
export const GET_USER = "GET_USER";
export const LOGOUT = "LOGOUT";
export const CLEAN_ALERT = "CLEAN_ALERT";

//DROPZONE FILES
export const UPLOAD_FILE = "UPLOAD_FILE";
export const UPLOADFILES_RIGHT = "UPLOADFILES_RIGHT";
export const UPLOADFILES_WRONG = "UPLOADFILES_WRONG";
export const CREATELINK_RIGHT = "CREATELINK_RIGHT";
export const CLEAN_STATE = "CLEAN_STATE";
export const ADD_PASSWORD = "ADD_PASSWORD";
export const ADD_DOWNLOADS = "ADD_DOWNLOADS";
export const VALIDATE_PASSWORD = "VALIDATE_PASSWORD";
